# Generated by Django 4.1.3 on 2022-11-18 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id_imovel', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('limite_hospedes', models.IntegerField()),
                ('banheiros', models.IntegerField()),
                ('pet_friendly', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='S', max_length=1)),
                ('valor_limpeza', models.FloatField(max_length=10)),
                ('data_ativacao', models.DateField()),
                ('criado_em', models.DateTimeField()),
                ('atualizado_em', models.DateTimeField()),
            ],
        ),
    ]
