# Generated by Django 4.1.3 on 2022-11-21 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('anuncio_id', models.AutoField(primary_key=True, serialize=False)),
                ('plataforma', models.CharField(max_length=30)),
                ('taxa_plataforma', models.FloatField(max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('imovel_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('limite_hospedes', models.IntegerField()),
                ('banheiros', models.IntegerField()),
                ('pet_friendly', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='N', max_length=1)),
                ('valor_limpeza', models.FloatField(max_length=10)),
                ('data_ativacao', models.DateField(auto_now_add=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('reserva_id', models.AutoField(primary_key=True, serialize=False)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('preco_total', models.FloatField(max_length=10)),
                ('comentarios', models.CharField(max_length=150)),
                ('numero_hospedes', models.IntegerField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('anuncio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desafio.anuncio')),
            ],
        ),
        migrations.AddField(
            model_name='anuncio',
            name='imovel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desafio.imovel'),
        ),
    ]
