# Generated by Django 4.1.3 on 2022-11-18 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id_imovel', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('plataforma', models.CharField(max_length=30)),
                ('taxa_plataforma', models.FloatField(max_length=10)),
                ('criado_em', models.DateTimeField()),
                ('atualizado_em', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('codigo_reserva', models.CharField(default=646, max_length=1000, primary_key=True, serialize=False)),
                ('plataforma', models.CharField(max_length=30)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('preco_total', models.FloatField(max_length=10)),
                ('comentarios', models.CharField(max_length=150)),
                ('numero_hospedes', models.IntegerField()),
                ('criado_em', models.DateTimeField()),
                ('atualizado_em', models.DateTimeField()),
            ],
        ),
    ]
